_BASE_: "robot_hu_config.yaml"

policy:
#  init_noise_std: 1.0
  init_noise_std: 0.2
  actor_class: "SimpleLSTM"
  critic_class: "SimpleLSTM"
  actor_hidden_dims: 64
  actor_num_layers: 2
  critic_hidden_dims: 64
  critic_num_layers: 1

algorithm:
  entropy_coef: 0.001
  learning_rate: 0.00001
  num_learning_epochs: 2
  gamma: 0.994
  lam: 0.9
  num_mini_batches: 4

runner:
  num_steps_per_env: 60
  max_iterations: 3001

  # deque
  max_actor_history: 10
  max_critic_history: 3

  # logging
  save_interval: 100
  experiment_name: 'HIT_Imitate_ppo_all_dof_mlp'
  run_name: '7.31-1-position'
