_BASE_: "robot_87_config.yaml"

robot:
  "robot_87_config.yaml"

policy:
  init_noise_std: 1.0
#  init_noise_std: 0.2
  actor_class: "SimpleMLP"
  critic_class: "SimpleMLP"
  actor_hidden_dims: [512, 256, 128]
  critic_hidden_dims: [768, 256, 128]

algorithm:
  entropy_coef: 0.001
  learning_rate: 0.00001
  num_learning_epochs: 2
  gamma: 0.994
  lam: 0.9
  num_mini_batches: 4

runner:
  num_steps_per_env: 60
  max_iterations: 8001

  # deque
  max_actor_history: 15
  max_critic_history: 3

  # logging
  save_interval: 50
  experiment_name: 'HIT_all_dof_mlp'
  run_name: '8.9-2-reference-position'
