USD_PATH:
#  "HIT_force/elec_robot_forxml_color.usd"
  "robot_simplify/robot_simplify.usd"
#  "robot_simplify/robot_simplify_colored.usd"

ROBOT_POS:
  [0., 0., 0.95]
#  [0., 0., 5]

ROBOT_ROT:
  [1, 0., 0., 0.]

VELOCITY:
  [1, 0, 0, 0, 0, 0]

FIXED_BASE:
  False
#  True

DISABLE_GRAVITY:
  False

END_EFFECTOR_NAME:
  left_foot: "l_foot"
  right_foot: "r_foot"

GAIT:
  30-run_HIT: 1
  slope_lone: 2
  squat_walk: 3
  stair_full: 4
  hit_save_people: 5
  forsquat_down: 6
  forsquat_up: 7
  squat_with_people: 8
  save_and_quit: 9

SIM:
  num_envs: 1
  env_spacing: 1
  device: "cuda:0"

CYCLE_TIME:
  0.64

#ACTION_POS:
#  left_leg_hip_roll: 0
#  left_leg_hip_yaw: 0
#  left_leg_hip_pitch: -0.35
#  left_leg_knee_pitch: -0.76
#  left_leg_ankle_pitch: -0.40
#  left_leg_ankle_roll: 0.0
#  #**********************************
#  right_leg_hip_roll: 0.0
#  right_leg_hip_yaw: 0
#  right_leg_hip_pitch: 0.35
#  right_leg_knee_pitch: 0.76
#  right_leg_ankle_pitch: 0.40
#  right_leg_ankle_roll: 0.0

INIT_JOINT_POS:
  #--------------hit_elec_squat.usd---------------------
  l_hip_roll: 0
  l_hip_yaw: 0
  l_hip_pitch: -0.25
  l_knee: -0.76
  l_ankle_pitch: -0.40
  l_ankle_roll: 0.0
  r_hip_roll: 0
  r_hip_yaw: 0
  r_hip_pitch: 0.35
  r_knee: 0.76
  r_ankle_pitch: 0.4
  r_ankle_roll: 0
  # --- all dof ---
  waist_yaw: 0
  waist_pitch: 0
  left_arm_pitch: 0
  left_arm_roll: 0
  left_arm_yaw: 0
  left_arm_forearm_pitch: 0
  right_arm_pitch: 0
#  right_arm_roll: -0.561930215
  right_arm_roll: 0
  right_arm_yaw: 0
  right_arm_forearm_pitch: 0

DOF_ASSET:
   l_hip_roll:
     effort_limit: 300.0
     velocity_limit: 100.0
     stiffness: 150.0
     damping: 5.0
   l_hip_yaw:
     effort_limit: 300.0
     velocity_limit: 100.0
     stiffness: 150.0
     damping: 5.0
   l_hip_pitch:
     effort_limit: 300.0
     velocity_limit: 100.0
     stiffness: 200
     damping: 5.0
   l_knee:
     effort_limit: 300
     velocity_limit: 100
#     stiffness: 550
     stiffness: 200
     damping: 5.0
   l_ankle_pitch:
     effort_limit: 20
     velocity_limit: 20
     stiffness: 20.0
     damping: 2
   l_ankle_roll:
     effort_limit: 20
     velocity_limit: 20
     stiffness: 20.0
     damping: 2.0
   r_hip_roll:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 150.0
     damping: 5.0
   r_hip_yaw:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 150.0
     damping: 5.0
   r_hip_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 200.0
     damping: 5.0
   r_knee:
     effort_limit: 300
     velocity_limit: 100
#     stiffness: 550.0
     stiffness: 200.0
     damping: 5.0
   r_ankle_pitch:
     effort_limit: 20
     velocity_limit: 20
     stiffness: 20.0
     damping: 2.0
   r_ankle_roll:
     effort_limit: 20
     velocity_limit: 20
     stiffness: 20.0
     damping: 2.0
   #--- all dof ---
   waist_yaw:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 200.0
     damping: 5.0
   waist_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 200.0
     damping: 5.0
   left_arm_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   left_arm_roll:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   left_arm_yaw:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   left_arm_forearm_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   right_arm_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   right_arm_roll:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   right_arm_yaw:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0
   right_arm_forearm_pitch:
     effort_limit: 300
     velocity_limit: 100
     stiffness: 40
     damping: 10.0


terrain:
  static_friction: 0.6
  dynamic_friction: 0.6
  restitution: 0.

normalization:
  obs_scales:
    dof_pos: 1
    dof_vel: 1
    quat: 1
    ang_vel: 1
