USD_PATH:
  "HIT_force/hit_elec_squat.usd"

ROBOT_POS:
  [0.0, 0.0, 1]

ROBOT_ROT:
  [1, 0., 0., 0.]

FIXED_BASE:
  True

DISABLE_GRAVITY:
  True

SIM:
  num_envs: 1
  env_spacing: 1
  device: "cuda:0"

CYCLE_TIME:
  0.64

#ACTION_POS:
#  left_leg_hip_roll: 0
#  left_leg_hip_yaw: 0
#  left_leg_hip_pitch: -0.35
#  left_leg_knee_pitch: -0.76
#  left_leg_ankle_pitch: -0.40
#  left_leg_ankle_roll: 0.0
#  #**********************************
#  right_leg_hip_roll: 0.0
#  right_leg_hip_yaw: 0
#  right_leg_hip_pitch: 0.35
#  right_leg_knee_pitch: 0.76
#  right_leg_ankle_pitch: 0.40
#  right_leg_ankle_roll: 0.0

INIT_JOINT_POS:
  #--------------hit_elec_squat.usd---------------------
  l_hip_roll: 0.0
  l_hip_yaw: 0.0
  l_hip_pitch: -0.35
  l_knee: 0.73
  l_ankle_pitch: -0.40
  l_ankle_roll: 0.0
  r_hip_roll: 0.0
  r_hip_yaw: 0.0
  r_hip_pitch: -0.35
  r_knee: 0.73
  r_ankle_pitch: -0.40
  r_ankle_roll: 0.0
  # --- all dof ---
  waist_yaw: 0.0
  waist_pitch: 0.0
  l_shoulder_pitch: 0.0
  l_shoulder_roll: 0
  l_shoulder_yaw: 0.0
  l_elbow: -1.178
  r_shoulder_pitch: 0.0
  r_shoulder_roll: 0
  r_shoulder_yaw: 0.0
  r_elbow: 1.178

DOF_ASSET:
   l_hip_roll:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350.0
     damping: 10.0
   l_hip_yaw:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350.0
     damping: 10.0
   l_hip_pitch:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350
     damping: 10.0
   l_knee:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   l_ankle_pitch:
     effort_limit: 300
     velocity_limit: 30
     stiffness: 350.0
     damping: 10.0
   l_ankle_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_knee:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_ankle_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_ankle_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   #--- all dof ---
   waist_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   waist_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 200.0
     damping: 50.0
   l_shoulder_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   l_shoulder_roll:
     effort_limit: 300
     velocity_limit: 320
     stiffness: 350
     damping: 10.0
   l_shoulder_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   l_elbow:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   r_shoulder_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   r_shoulder_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   r_shoulder_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   r_elbow:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0


terrain:
  static_friction: 0.6
  dynamic_friction: 0.6
  restitution: 0.

normalization:
  obs_scales:
    dof_pos: 1
    dof_vel: 0.05
    quat: 1
    ang_vel: 1
