USD_PATH:
  "HIT_force/elec_robot_forxml_color.usd"

ROBOT_POS:
  [0., 0., 0.88]

ROBOT_ROT:
  [1, 0., 0., 0.]

REFERENCE_OFFSET:
  [1, 0, -0.065]

VELOCITY:
  [2.2, 0, 0]

FIXED_BASE:
  False

DISABLE_GRAVITY:
  False

END_EFFECTOR_NAME:
  left_foot: "l_foot"
  right_foot: "r_foot"

GAIT:
  30-run_HIT: 1
  slope_lone: 2
  squat_walk: 3
  stair_full: 4
  hit_save_people: 5
  forsquat_down: 6
  forsquat_up: 7

SIM:
  num_envs: 1
  env_spacing: 1
  device: "cuda:0"

CYCLE_TIME:
  0.64

#ACTION_POS:
#  left_leg_hip_roll: 0
#  left_leg_hip_yaw: 0
#  left_leg_hip_pitch: -0.35
#  left_leg_knee_pitch: -0.76
#  left_leg_ankle_pitch: -0.40
#  left_leg_ankle_roll: 0.0
#  #**********************************
#  right_leg_hip_roll: 0.0
#  right_leg_hip_yaw: 0
#  right_leg_hip_pitch: 0.35
#  right_leg_knee_pitch: 0.76
#  right_leg_ankle_pitch: 0.40
#  right_leg_ankle_roll: 0.0

INIT_JOINT_POS:
  #--------------hit_elec_squat.usd---------------------
  l_hip_roll: -0.12978186
  l_hip_yaw: -0.010762034
  l_hip_pitch: 0.219413995
  l_knee: -0.378585505
  l_ankle_pitch: -0.471593808
  l_ankle_roll: 0.0
  r_hip_roll: -0.070190828
  r_hip_yaw: 0.009044493
  r_hip_pitch: 0.536524408
  r_knee: 1.427066338
  r_ankle_pitch: -0.099026858
  r_ankle_roll: 0
  # --- all dof ---
  waist_yaw: 0.006977122
  waist_pitch: -0.422990454
  left_arm_pitch: 0.259341818
  left_arm_roll: 0.179169593
  left_arm_yaw: -0.027985491
  left_arm_forearm_pitch: -1.585207336
  right_arm_pitch: 0.144874375
  right_arm_roll: -0.561930215
  right_arm_yaw: 0.001333859
  right_arm_forearm_pitch: -1.203534075

DOF_ASSET:
   l_hip_roll:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350.0
     damping: 10.0
   l_hip_yaw:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350.0
     damping: 10.0
   l_hip_pitch:
     effort_limit: 300.0
     velocity_limit: 20.0
     stiffness: 350
     damping: 10.0
   l_knee:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   l_ankle_pitch:
     effort_limit: 300
     velocity_limit: 30
     stiffness: 350.0
     damping: 10.0
   l_ankle_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_hip_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_knee:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_ankle_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   r_ankle_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   #--- all dof ---
   waist_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 10.0
   waist_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350.0
     damping: 50.0
   left_arm_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   left_arm_roll:
     effort_limit: 300
     velocity_limit: 320
     stiffness: 350
     damping: 10.0
   left_arm_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   left_arm_forearm_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   right_arm_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   right_arm_roll:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   right_arm_yaw:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0
   right_arm_forearm_pitch:
     effort_limit: 300
     velocity_limit: 20
     stiffness: 350
     damping: 10.0


terrain:
  static_friction: 0.6
  dynamic_friction: 0.6
  restitution: 0.

normalization:
  obs_scales:
    dof_pos: 1
    dof_vel: 1
    quat: 1
    ang_vel: 1
